FIBO	START	4
FIRST	CLEAR	X
	LDS	#1
	LDT	ZERO
LOOP	STS	CURR
	ADDR	T, S
	LDT	CURR
	TIX	TEST
	JLT	LOOP	.SHOULD BE PC RELATIVE
ZERO	BYTE	X'00'
CURR	RESB	1
TEST	BYTE	C'EOF'	.10 NUMBERS OF THE SEQUENCE
	END	FIRST
