MACROS	MACRO	4
RDBUFF	MACRO	X
		.	
		.
		.
		MEND	CURR
WRBUFF	MACRO	S
		.	CURR
		MEND	TEST
	JLT	LOOP	.SHOULD BE PC RELATIVE
MACROX	MACRO	X'00'
CURR	RESB	1
TEST	BYTE	C'EOF'	.10 NUMBERS OF THE SEQUENCE
	END	FIRST
